### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by bubuleur** [mancuniancol/script.magnetic.t411-mc#2]
Hello,
I come to you if it was possible to change the file icon.png by this one
![icon](https://cloud.githubusercontent.com/assets/21688137/21179685/73e7799a-c1f5-11e6-95d7-51af995a0232.png)
The existing one has display problems
In thanking you
Cordially

**Comment by mancuniancol** [comment]
Thank you, I usually use the same of the website.  But, you are right. Sometimes, it doesn't display properly.

I will added it right now.
